/* Automatically generated by
	VMPluginCodeGenerator VMMaker.oscog-cb.2351 uuid: 35506f97-fa9a-42db-bcb3-2c263d37afa1
   from
	SkiaPlugin *  uuid: nil
 */
static char __buildInfo[] = "SkiaPlugin *  uuid: nil " __DATE__ ;



#include "config.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* Default EXPORT macro that does nothing (see comment in sq.h): */
#define EXPORT(returnType) returnType

/* Do not include the entire sq.h file but just those parts needed. */
#include "sqConfig.h"			/* Configuration options */
#include "sqVirtualMachine.h"	/*  The virtual machine proxy definition */
#include "sqPlatformSpecific.h"	/* Platform specific definitions */

#define true 1
#define false 0
#define null 0  /* using 'null' because nil is predefined in Think C */
#ifdef SQUEAK_BUILTIN_PLUGIN
# undef EXPORT
# define EXPORT(returnType) static returnType
#endif

#include "SkiaPlugin.h"
#include "sqMemoryAccess.h"


/*** Function Prototypes ***/
EXPORT(const char*) getModuleName(void);
EXPORT(sqInt) primitiveCanvasClipRect(void);
EXPORT(sqInt) primitiveCanvasConcatTransform(void);
EXPORT(sqInt) primitiveCanvasCopyTransform(void);
EXPORT(sqInt) primitiveCanvasDrawCircle(void);
EXPORT(sqInt) primitiveCanvasDrawColor(void);
EXPORT(sqInt) primitiveCanvasDrawLine(void);
EXPORT(sqInt) primitiveCanvasDrawOval(void);
EXPORT(sqInt) primitiveCanvasDrawRect(void);
EXPORT(sqInt) primitiveCanvasDrawRoundedRect(void);
EXPORT(sqInt) primitiveCanvasDrawRoundedRectRadii(void);
EXPORT(sqInt) primitiveCanvasDrawText(void);
EXPORT(sqInt) primitiveCanvasResetMatrix(void);
EXPORT(sqInt) primitiveCanvasRestore(void);
EXPORT(sqInt) primitiveCanvasSave(void);
EXPORT(sqInt) primitiveCanvasScale(void);
EXPORT(sqInt) primitiveCanvasTranslate(void);
EXPORT(sqInt) primitiveCreateCanvas(void);
EXPORT(sqInt) primitiveCreateDefaultTypeface(void);
EXPORT(sqInt) primitiveCreateFontStyle(void);
EXPORT(sqInt) primitiveCreatePaint(void);
EXPORT(sqInt) primitiveCreateSurface(void);
EXPORT(sqInt) primitiveCreateTypefaceFromName(void);
EXPORT(sqInt) primitiveDeleteCanvas(void);
EXPORT(sqInt) primitiveDeletePaint(void);
EXPORT(sqInt) primitiveDeleteSurface(void);
EXPORT(sqInt) primitivePaintGetFontMetrics(void);
EXPORT(sqInt) primitivePaintMeasureText(void);
EXPORT(sqInt) primitivePaintSetAntialias(void);
EXPORT(sqInt) primitivePaintSetColor(void);
EXPORT(sqInt) primitivePaintSetStroke(void);
EXPORT(sqInt) primitivePaintSetStrokeJoin(void);
EXPORT(sqInt) primitivePaintSetStrokeMiter(void);
EXPORT(sqInt) primitivePaintSetStrokeWidth(void);
EXPORT(sqInt) primitivePaintSetTextSize(void);
EXPORT(sqInt) primitivePaintSetTypeface(void);
EXPORT(sqInt) primitivePaintSetTypefaceFromName(void);
EXPORT(sqInt) primitiveSaveSurface(void);
EXPORT(sqInt) setInterpreter(struct VirtualMachine*anInterpreter);


/*** Variables ***/

#if !defined(SQUEAK_BUILTIN_PLUGIN)
static sqInt (*booleanValueOf)(sqInt obj);
static sqInt (*byteSizeOf)(sqInt oop);
static sqInt (*classBitmap)(void);
static sqInt (*failed)(void);
static void * (*fetchArrayofObject)(sqInt fieldIndex, sqInt objectPointer);
static sqInt (*fetchClassOf)(sqInt oop);
static sqInt (*fetchIntegerofObject)(sqInt fieldIndex, sqInt objectPointer);
static sqInt (*fetchPointerofObject)(sqInt index, sqInt oop);
static void * (*firstIndexableField)(sqInt oop);
static sqInt (*floatObjectOf)(double  aFloat);
static sqInt (*isPointers)(sqInt oop);
static sqInt (*pop)(sqInt nItems);
static sqInt (*popthenPush)(sqInt nItems, sqInt oop);
static sqInt (*positive32BitIntegerFor)(unsigned int integerValue);
static sqInt (*primitiveFail)(void);
static sqInt (*primitiveFailFor)(sqInt reasonCode);
static sqInt (*push)(sqInt object);
static sqInt (*pushInteger)(sqInt integerValue);
static sqInt (*slotSizeOf)(sqInt oop);
static double (*stackFloatValue)(sqInt offset);
static sqInt (*stackIntegerValue)(sqInt offset);
static sqInt (*stackObjectValue)(sqInt offset);
static sqInt (*stackValue)(sqInt offset);
#else /* !defined(SQUEAK_BUILTIN_PLUGIN) */
extern sqInt booleanValueOf(sqInt obj);
extern sqInt byteSizeOf(sqInt oop);
extern sqInt classBitmap(void);
extern sqInt failed(void);
extern void * fetchArrayofObject(sqInt fieldIndex, sqInt objectPointer);
extern sqInt fetchClassOf(sqInt oop);
extern sqInt fetchIntegerofObject(sqInt fieldIndex, sqInt objectPointer);
extern sqInt fetchPointerofObject(sqInt index, sqInt oop);
extern void * firstIndexableField(sqInt oop);
extern sqInt floatObjectOf(double  aFloat);
extern sqInt isPointers(sqInt oop);
extern sqInt pop(sqInt nItems);
extern sqInt popthenPush(sqInt nItems, sqInt oop);
extern sqInt positive32BitIntegerFor(unsigned int integerValue);
extern sqInt primitiveFail(void);
extern sqInt primitiveFailFor(sqInt reasonCode);
extern sqInt push(sqInt object);
extern sqInt pushInteger(sqInt integerValue);
extern sqInt slotSizeOf(sqInt oop);
extern double stackFloatValue(sqInt offset);
extern sqInt stackIntegerValue(sqInt offset);
extern sqInt stackObjectValue(sqInt offset);
extern sqInt stackValue(sqInt offset);
extern
#endif
struct VirtualMachine* interpreterProxy;
static const char *moduleName =
#ifdef SQUEAK_BUILTIN_PLUGIN
	"SkiaPlugin *  (i)"
#else
	"SkiaPlugin *  (e)"
#endif
;



/*	Note: This is hardcoded so it can be run from Squeak.
	The module name is used for validating a module *after*
	it is loaded to check if it does really contain the module
	we're thinking it contains. This is important! */

	/* InterpreterPlugin>>#getModuleName */
EXPORT(const char*)
getModuleName(void)
{
	return moduleName;
}

	/* SkiaPlugin>>#primitiveCanvasClipRect */
EXPORT(sqInt)
primitiveCanvasClipRect(void)
{
    double bottom;
    sqInt canvas;
    double left;
    double right;
    double top;

	canvas = stackIntegerValue(4);
	left = stackFloatValue(3);
	right = stackFloatValue(2);
	top = stackFloatValue(1);
	bottom = stackFloatValue(0);
	
	sk_rect_t rect;
	rect.left = left;
	rect.top = top;
	rect.right = right;
	rect.bottom = bottom;
	sk_canvas_clip_rect((sk_canvas_t*) toPointer(canvas), &rect);
	pop(5);
	return 0;
}

	/* SkiaPlugin>>#primitiveCanvasConcatTransform */
EXPORT(sqInt)
primitiveCanvasConcatTransform(void)
{
    float *buffer;
    sqInt canvas;
    sqInt matrix;

	canvas = stackIntegerValue(1);
	matrix = stackValue(0);
	buffer = firstIndexableField(matrix);
	
	sk_matrix_t sk_matrix;
	sk_matrix.mat[0] = buffer[0];
	sk_matrix.mat[1] = buffer[1];
	sk_matrix.mat[2] = buffer[2];
	sk_matrix.mat[3] = buffer[3];
	sk_matrix.mat[4] = buffer[4];
	sk_matrix.mat[5] = buffer[5];
	sk_matrix.mat[6] = 0;
	sk_matrix.mat[7] = 0;
	sk_matrix.mat[8] = 1;
	sk_canvas_concat((sk_canvas_t *) toPointer(canvas), &sk_matrix);
	pop(2);
	return 0;
}

	/* SkiaPlugin>>#primitiveCanvasCopyTransform */
EXPORT(sqInt)
primitiveCanvasCopyTransform(void)
{
    sqInt fromCanvas;
    sqInt toCanvas;

	fromCanvas = stackIntegerValue(1);
	toCanvas = stackIntegerValue(0);
	sk_canvas_copy_transform((sk_canvas_t *) toPointer(fromCanvas), toPointer(toCanvas));
	pop(2);
	return 0;
}

	/* SkiaPlugin>>#primitiveCanvasDrawCircle */
EXPORT(sqInt)
primitiveCanvasDrawCircle(void)
{
    sqInt canvas;
    double cx;
    double cy;
    sqInt paint;
    double radius;

	canvas = stackIntegerValue(4);
	cx = stackFloatValue(3);
	cy = stackFloatValue(2);
	radius = stackFloatValue(1);
	paint = stackIntegerValue(0);
	sk_canvas_draw_circle((sk_canvas_t *) toPointer(canvas), cx, cy, radius, (sk_paint_t *) toPointer(paint));
	pop(5);
	return 0;
}

	/* SkiaPlugin>>#primitiveCanvasDrawColor */
EXPORT(sqInt)
primitiveCanvasDrawColor(void)
{
    sqInt blend;
    sqInt canvas;
    sqInt color;

	canvas = stackIntegerValue(2);
	color = stackIntegerValue(1);
	blend = stackIntegerValue(0);
	sk_canvas_draw_color((sk_canvas_t *) toPointer(canvas), color, blend);
	pop(3);
	return 0;
}

	/* SkiaPlugin>>#primitiveCanvasDrawLine */
EXPORT(sqInt)
primitiveCanvasDrawLine(void)
{
    sqInt canvas;
    sqInt paint;
    double x0;
    double x1;
    double y0;
    double y1;

	canvas = stackIntegerValue(5);
	x0 = stackFloatValue(4);
	y0 = stackFloatValue(3);
	x1 = stackFloatValue(2);
	y1 = stackFloatValue(1);
	paint = stackIntegerValue(0);
	sk_canvas_draw_line((sk_canvas_t *) toPointer(canvas), x0, y0, x1, y1, (sk_paint_t *) toPointer(paint));
	pop(6);
	return 0;
}

	/* SkiaPlugin>>#primitiveCanvasDrawOval */
EXPORT(sqInt)
primitiveCanvasDrawOval(void)
{
    double bottom;
    sqInt canvas;
    double left;
    sqInt paint;
    double right;
    double top;

	canvas = stackIntegerValue(5);
	left = stackFloatValue(4);
	right = stackFloatValue(3);
	top = stackFloatValue(2);
	bottom = stackFloatValue(1);
	paint = stackIntegerValue(0);
	
	sk_rect_t rect;
	rect.left = left;
	rect.top = top;
	rect.right = right;
	rect.bottom = bottom;
	sk_canvas_draw_oval((sk_canvas_t *) toPointer(canvas), &rect, (sk_paint_t *) toPointer(paint));
	pop(6);
	return 0;
}

	/* SkiaPlugin>>#primitiveCanvasDrawRect */
EXPORT(sqInt)
primitiveCanvasDrawRect(void)
{
    double bottom;
    sqInt canvas;
    double left;
    sqInt paint;
    double right;
    double top;

	canvas = stackIntegerValue(5);
	left = stackFloatValue(4);
	right = stackFloatValue(3);
	top = stackFloatValue(2);
	bottom = stackFloatValue(1);
	paint = stackIntegerValue(0);
	
	sk_rect_t rect;
	rect.left = left;
	rect.top = top;
	rect.right = right;
	rect.bottom = bottom;
	sk_canvas_draw_rect((sk_canvas_t *) toPointer(canvas), &rect, (sk_paint_t *) toPointer(paint));
	pop(6);
	return 0;
}

	/* SkiaPlugin>>#primitiveCanvasDrawRoundedRect */
EXPORT(sqInt)
primitiveCanvasDrawRoundedRect(void)
{
    double bottom;
    sqInt canvas;
    double left;
    sqInt paint;
    double radiusX;
    double radiusY;
    double right;
    double top;

	canvas = stackIntegerValue(7);
	left = stackFloatValue(6);
	right = stackFloatValue(5);
	top = stackFloatValue(4);
	bottom = stackFloatValue(3);
	radiusX = stackFloatValue(2);
	radiusY = stackFloatValue(1);
	paint = stackIntegerValue(0);
	sk_canvas_draw_rounded_rect((sk_canvas_t *) toPointer(canvas), left, right, top, bottom, radiusX, radiusY, (sk_paint_t *)  toPointer(paint));
	pop(8);
	return 0;
}

	/* SkiaPlugin>>#primitiveCanvasDrawRoundedRectRadii */
EXPORT(sqInt)
primitiveCanvasDrawRoundedRectRadii(void)
{
    double bottom;
    sqInt canvas;
    double left;
    double llX;
    double llY;
    double lrX;
    double lrY;
    sqInt paint;
    double right;
    double tlX;
    sqInt tlY;
    double top;
    double trX;
    double trY;

	canvas = stackIntegerValue(13);
	left = stackFloatValue(12);
	right = stackFloatValue(11);
	top = stackFloatValue(10);
	bottom = stackFloatValue(9);
	tlX = stackFloatValue(8);
	tlY = stackFloatValue(7);
	trX = stackFloatValue(6);
	trY = stackFloatValue(5);
	lrX = stackFloatValue(4);
	lrY = stackFloatValue(3);
	llX = stackFloatValue(2);
	llY = stackFloatValue(1);
	paint = stackIntegerValue(0);
	sk_canvas_draw_rounded_rect_radii((sk_canvas_t *) toPointer(canvas), left, right, top, bottom, tlX, tlY, trX, trY, lrX, lrY, llX, llY, (sk_paint_t *)  toPointer(paint));
	pop(14);
	return 0;
}

	/* SkiaPlugin>>#primitiveCanvasDrawText */
EXPORT(sqInt)
primitiveCanvasDrawText(void)
{
    sqInt canvas;
    sqInt len;
    sqInt paint;
    char *text;
    sqInt textObj;
    double x;
    double y;

	canvas = stackIntegerValue(4);
	textObj = stackValue(3);
	x = stackFloatValue(2);
	y = stackFloatValue(1);
	paint = stackIntegerValue(0);
	if (failed()) {
		primitiveFail();
	}
	text = firstIndexableField(textObj);
	len = byteSizeOf(textObj);
	sk_canvas_draw_text((sk_canvas_t *) toPointer(canvas), text, len, x, y, (sk_paint_t *) toPointer(paint));
	pop(5);
	return 0;
}

	/* SkiaPlugin>>#primitiveCanvasResetMatrix */
EXPORT(sqInt)
primitiveCanvasResetMatrix(void)
{
    sqInt canvas;

	canvas = stackIntegerValue(0);
	sk_canvas_reset_matrix((sk_canvas_t *) toPointer(canvas));
	pop(1);
	return 0;
}

	/* SkiaPlugin>>#primitiveCanvasRestore */
EXPORT(sqInt)
primitiveCanvasRestore(void)
{
    sqInt canvas;

	canvas = stackIntegerValue(0);
	sk_canvas_restore((sk_canvas_t *) toPointer(canvas));
	pop(1);
	return 0;
}

	/* SkiaPlugin>>#primitiveCanvasSave */
EXPORT(sqInt)
primitiveCanvasSave(void)
{
    sqInt canvas;

	canvas = stackIntegerValue(0);
	sk_canvas_save((sk_canvas_t *) toPointer(canvas));
	pop(1);
	return 0;
}

	/* SkiaPlugin>>#primitiveCanvasScale */
EXPORT(sqInt)
primitiveCanvasScale(void)
{
    sqInt canvas;
    double x;
    double y;

	canvas = stackIntegerValue(2);
	x = stackFloatValue(1);
	y = stackFloatValue(0);
	sk_canvas_translate((sk_canvas_t *) toPointer(canvas), x, y);
	pop(3);
	return 0;
}

	/* SkiaPlugin>>#primitiveCanvasTranslate */
EXPORT(sqInt)
primitiveCanvasTranslate(void)
{
    sqInt canvas;
    double x;
    double y;

	canvas = stackIntegerValue(2);
	x = stackFloatValue(1);
	y = stackFloatValue(0);
	sk_canvas_translate((sk_canvas_t *) toPointer(canvas), x, y);
	pop(3);
	return 0;
}

	/* SkiaPlugin>>#primitiveCreateCanvas */
EXPORT(sqInt)
primitiveCreateCanvas(void)
{
    sqInt canvas;
    sqInt surface;

	surface = stackIntegerValue(0);
	canvas = 0;
	canvas = toHandle(sk_surface_get_canvas((sk_surface_t *) toPointer(surface)));
	pop(2);
	return pushInteger(canvas);
}

	/* SkiaPlugin>>#primitiveCreateDefaultTypeface */
EXPORT(sqInt)
primitiveCreateDefaultTypeface(void)
{
    sqInt t;

	t = 0;
	t = toHandle(sk_typeface_new_default());
	pop(1);
	pushInteger(t);
	return 0;
}

	/* SkiaPlugin>>#primitiveCreateFontStyle */
EXPORT(sqInt)
primitiveCreateFontStyle(void)
{
    sqInt slant;
    uint32_t style;
    sqInt weight;
    sqInt width;

	weight = stackIntegerValue(2);
	width = stackIntegerValue(1);
	slant = stackIntegerValue(0);
	style = 0;
	style = sk_font_style_create(weight, width, slant);
	pop(4);
	return push(positive32BitIntegerFor(style));
}

	/* SkiaPlugin>>#primitiveCreatePaint */
EXPORT(sqInt)
primitiveCreatePaint(void)
{
    sqInt paint;

	paint = 0;
	paint = toHandle(sk_paint_new());
	pop(1);
	pushInteger(paint);
	return 0;
}

	/* SkiaPlugin>>#primitiveCreateSurface */
EXPORT(sqInt)
primitiveCreateSurface(void)
{
    sqInt bmBits;
    sqInt bmDepth;
    sqInt bmHeight;
    sqInt bmWidth;
    void *buffer;
    sqInt formOop;
    sqInt surface;

	formOop = stackObjectValue(0);
	if (!(isPointers(formOop))) {
		return primitiveFailFor(105);
	}
	if ((slotSizeOf(formOop)) < 5) {
		return primitiveFailFor(106);
	}
	bmBits = fetchPointerofObject(0, formOop);
	if (!((fetchClassOf(bmBits)) == (classBitmap()))) {
		return primitiveFailFor(107);
	}
	bmWidth = fetchIntegerofObject(1, formOop);
	bmHeight = fetchIntegerofObject(2, formOop);
	bmDepth = fetchIntegerofObject(3, formOop);
	buffer = ((void*) (fetchArrayofObject(0, formOop)));
	if (failed()) {
		return primitiveFailFor(108);
	}
	if (!((bmWidth >= 0)
		 && (bmHeight >= 0))) {
		return primitiveFailFor(109);
	}
	surface = 0;
	sk_imageinfo_t info;
	info.width = bmWidth;
	info.height = bmHeight;
	info.colorType = BGRA_8888_SK_COLORTYPE;//sq_color_type_for_depth(bmDepth);
	info.alphaType = UNPREMUL_SK_ALPHATYPE;//sq_alpha_type_for_depth(bmDepth);
	surface = toHandle(sk_surface_new_raster_direct(&info, buffer, bmWidth * 4, NULL));
	if (surface == 0) {
		return primitiveFailFor(100);
	}
	pop(2);
	return pushInteger(surface);
}

	/* SkiaPlugin>>#primitiveCreateTypefaceFromName */
EXPORT(sqInt)
primitiveCreateTypefaceFromName(void)
{
    sqInt fontStyle;
    sqInt len;
    char*name;
    sqInt nameObj;
    sqInt t;

	nameObj = stackValue(1);
	fontStyle = stackIntegerValue(0);
	name = firstIndexableField(nameObj);
	len = byteSizeOf(nameObj);
	t = 0;
	
	char *name_nt = malloc(sizeof(char) * (len + 1));
	strncpy(name_nt, name, len);
	name_nt[len] = 0;
	t = toHandle(sk_typeface_new_from_name(name_nt, fontStyle));
	free(name_nt);
	pop(3);
	pushInteger(t);
	return 0;
}

	/* SkiaPlugin>>#primitiveDeleteCanvas */
EXPORT(sqInt)
primitiveDeleteCanvas(void)
{
    sqInt canvas;


	/* the canvas is owned by its surface, so we only free the pointer slot */
	canvas = stackIntegerValue(0);
	freeHandle(canvas);
	pop(1);
	return 0;
}

	/* SkiaPlugin>>#primitiveDeletePaint */
EXPORT(sqInt)
primitiveDeletePaint(void)
{
    sqInt paint;

	paint = stackIntegerValue(0);
	
	sk_paint_delete((sk_paint_t *) toPointer(paint));
	freeHandle(paint);
	pop(1);
	return 0;
}

	/* SkiaPlugin>>#primitiveDeleteSurface */
EXPORT(sqInt)
primitiveDeleteSurface(void)
{
    sqInt surface;

	surface = stackIntegerValue(0);
	
	sk_surface_unref((sk_surface_t *) toPointer(surface));
	freeHandle(surface);
	pop(1);
	return 0;
}

	/* SkiaPlugin>>#primitivePaintGetFontMetrics */
EXPORT(sqInt)
primitivePaintGetFontMetrics(void)
{
    sqInt metricsObj;
    sqInt paint;

	paint = stackIntegerValue(1);

	/* interpreterProxy storePointer: 0 ofObject: metricsObj withValue: (interpreterProxy floatObjectOf: 1.0). */
	metricsObj = stackValue(0);
	sk_paint_get_font_metrics((sk_paint_t *) toPointer(paint), metricsObj);
	popthenPush(3, metricsObj);
	return 0;
}

	/* SkiaPlugin>>#primitivePaintMeasureText */
EXPORT(sqInt)
primitivePaintMeasureText(void)
{
    double advance;
    sqInt len;
    sqInt paint;
    char*text;
    sqInt textObj;

	paint = stackIntegerValue(1);
	textObj = stackValue(0);
	text = firstIndexableField(textObj);
	len = byteSizeOf(textObj);
	advance = sk_paint_measure_text((sk_paint_t *) toPointer(paint), text, len);
	popthenPush(3, floatObjectOf(advance));
	return 0;
}

	/* SkiaPlugin>>#primitivePaintSetAntialias */
EXPORT(sqInt)
primitivePaintSetAntialias(void)
{
    sqInt antialias;
    sqInt paint;

	paint = stackIntegerValue(1);
	antialias = booleanValueOf(stackValue(0));
	sk_paint_set_antialias((sk_paint_t *) toPointer(paint), antialias);
	pop(2);
	return 0;
}

	/* SkiaPlugin>>#primitivePaintSetColor */
EXPORT(sqInt)
primitivePaintSetColor(void)
{
    sqInt color;
    sqInt paint;

	paint = stackIntegerValue(1);
	color = stackIntegerValue(0);
	sk_paint_set_color((sk_paint_t *) toPointer(paint), color);
	pop(2);
	return 0;
}

	/* SkiaPlugin>>#primitivePaintSetStroke */
EXPORT(sqInt)
primitivePaintSetStroke(void)
{
    sqInt paint;
    sqInt stroke;

	paint = stackIntegerValue(1);
	stroke = booleanValueOf(stackValue(0));
	sk_paint_set_stroke((sk_paint_t *) toPointer(paint), stroke);
	pop(2);
	return 0;
}


/*	0 ->MITER, 1 -> ROUND, 2 -> BEVEL */

	/* SkiaPlugin>>#primitivePaintSetStrokeJoin */
EXPORT(sqInt)
primitivePaintSetStrokeJoin(void)
{
    sqInt miter;
    sqInt paint;

	paint = stackIntegerValue(1);
	miter = stackIntegerValue(0);
	sk_paint_set_stroke_join((sk_paint_t *) toPointer(paint), miter);
	pop(2);
	return 0;
}


/*	0 -> BUTT, 1 -> ROUND, 2 -> SQUARE */

	/* SkiaPlugin>>#primitivePaintSetStrokeMiter */
EXPORT(sqInt)
primitivePaintSetStrokeMiter(void)
{
    sqInt miter;
    sqInt paint;

	paint = stackIntegerValue(1);
	miter = stackIntegerValue(0);
	sk_paint_set_stroke_miter((sk_paint_t *) toPointer(paint), miter);
	pop(2);
	return 0;
}

	/* SkiaPlugin>>#primitivePaintSetStrokeWidth */
EXPORT(sqInt)
primitivePaintSetStrokeWidth(void)
{
    sqInt paint;
    sqInt width;

	paint = stackIntegerValue(1);
	width = stackFloatValue(0);
	sk_paint_set_stroke_width((sk_paint_t *) toPointer(paint), width);
	pop(2);
	return 0;
}

	/* SkiaPlugin>>#primitivePaintSetTextSize */
EXPORT(sqInt)
primitivePaintSetTextSize(void)
{
    sqInt paint;
    double size;

	paint = stackIntegerValue(1);
	size = stackFloatValue(0);
	sk_paint_set_text_size((sk_paint_t *) toPointer(paint), size);
	pop(2);
	return 0;
}

	/* SkiaPlugin>>#primitivePaintSetTypeface */
EXPORT(sqInt)
primitivePaintSetTypeface(void)
{
    sqInt paint;
    sqInt typeface;

	paint = stackIntegerValue(1);
	typeface = stackIntegerValue(0);
	sk_paint_set_typeface((sk_paint_t *) toPointer(paint), (sk_typeface_t *) toPointer(typeface));
	pop(2);
	return 0;
}

	/* SkiaPlugin>>#primitivePaintSetTypefaceFromName */
EXPORT(sqInt)
primitivePaintSetTypefaceFromName(void)
{
    sqInt fontStyle;
    sqInt len;
    char*name;
    sqInt nameObj;
    sqInt paint;

	paint = stackIntegerValue(2);
	nameObj = stackValue(1);
	fontStyle = stackIntegerValue(0);
	name = firstIndexableField(nameObj);
	len = byteSizeOf(nameObj);
	
	char *name_nt = malloc(sizeof(char) * (len + 1));
	strncpy(name_nt, name, len);
	name_nt[len] = 0;
	sk_paint_set_typeface_from_name((sk_paint_t *) toPointer(paint), name_nt, fontStyle);
	free(name_nt);
	pop(3);
	return 0;
}

	/* SkiaPlugin>>#primitiveSaveSurface */
EXPORT(sqInt)
primitiveSaveSurface(void)
{
    sqInt surface;

	surface = stackIntegerValue(0);
	sk_image_t *image = sk_surface_new_image_snapshot((sk_surface_t *) toPointer(surface));
	sk_data_t *data = sk_image_encode(image);
	
	FILE *f = fopen("test.png", "w");
	fwrite(sk_data_get_data(data), sk_data_get_size(data), 1, f);
	fclose(f);
	return 0;
}


/*	Note: This is coded so that it can be run in Squeak. */

	/* InterpreterPlugin>>#setInterpreter: */
EXPORT(sqInt)
setInterpreter(struct VirtualMachine*anInterpreter)
{
    sqInt ok;

	interpreterProxy = anInterpreter;
	ok = ((interpreterProxy->majorVersion()) == (VM_PROXY_MAJOR))
	 && ((interpreterProxy->minorVersion()) >= (VM_PROXY_MINOR));
	if (ok) {
		
#if !defined(SQUEAK_BUILTIN_PLUGIN)
		booleanValueOf = interpreterProxy->booleanValueOf;
		byteSizeOf = interpreterProxy->byteSizeOf;
		classBitmap = interpreterProxy->classBitmap;
		failed = interpreterProxy->failed;
		fetchArrayofObject = interpreterProxy->fetchArrayofObject;
		fetchClassOf = interpreterProxy->fetchClassOf;
		fetchIntegerofObject = interpreterProxy->fetchIntegerofObject;
		fetchPointerofObject = interpreterProxy->fetchPointerofObject;
		firstIndexableField = interpreterProxy->firstIndexableField;
		floatObjectOf = interpreterProxy->floatObjectOf;
		isPointers = interpreterProxy->isPointers;
		pop = interpreterProxy->pop;
		popthenPush = interpreterProxy->popthenPush;
		positive32BitIntegerFor = interpreterProxy->positive32BitIntegerFor;
		primitiveFail = interpreterProxy->primitiveFail;
		primitiveFailFor = interpreterProxy->primitiveFailFor;
		push = interpreterProxy->push;
		pushInteger = interpreterProxy->pushInteger;
		slotSizeOf = interpreterProxy->slotSizeOf;
		stackFloatValue = interpreterProxy->stackFloatValue;
		stackIntegerValue = interpreterProxy->stackIntegerValue;
		stackObjectValue = interpreterProxy->stackObjectValue;
		stackValue = interpreterProxy->stackValue;
#endif /* !defined(SQUEAK_BUILTIN_PLUGIN) */
	}
	return ok;
}


#ifdef SQUEAK_BUILTIN_PLUGIN

static char _m[] = "SkiaPlugin";
void* SkiaPlugin_exports[][3] = {
	{(void*)_m, "getModuleName", (void*)getModuleName},
	{(void*)_m, "primitiveCanvasClipRect\000\000", (void*)primitiveCanvasClipRect},
	{(void*)_m, "primitiveCanvasConcatTransform\000\001", (void*)primitiveCanvasConcatTransform},
	{(void*)_m, "primitiveCanvasCopyTransform\000\000", (void*)primitiveCanvasCopyTransform},
	{(void*)_m, "primitiveCanvasDrawCircle\000\000", (void*)primitiveCanvasDrawCircle},
	{(void*)_m, "primitiveCanvasDrawColor\000\000", (void*)primitiveCanvasDrawColor},
	{(void*)_m, "primitiveCanvasDrawLine\000\000", (void*)primitiveCanvasDrawLine},
	{(void*)_m, "primitiveCanvasDrawOval\000\000", (void*)primitiveCanvasDrawOval},
	{(void*)_m, "primitiveCanvasDrawRect\000\000", (void*)primitiveCanvasDrawRect},
	{(void*)_m, "primitiveCanvasDrawRoundedRect\000\000", (void*)primitiveCanvasDrawRoundedRect},
	{(void*)_m, "primitiveCanvasDrawRoundedRectRadii\000\000", (void*)primitiveCanvasDrawRoundedRectRadii},
	{(void*)_m, "primitiveCanvasDrawText\000\001", (void*)primitiveCanvasDrawText},
	{(void*)_m, "primitiveCanvasResetMatrix\000\000", (void*)primitiveCanvasResetMatrix},
	{(void*)_m, "primitiveCanvasRestore\000\000", (void*)primitiveCanvasRestore},
	{(void*)_m, "primitiveCanvasSave\000\000", (void*)primitiveCanvasSave},
	{(void*)_m, "primitiveCanvasScale\000\000", (void*)primitiveCanvasScale},
	{(void*)_m, "primitiveCanvasTranslate\000\000", (void*)primitiveCanvasTranslate},
	{(void*)_m, "primitiveCreateCanvas\000\000", (void*)primitiveCreateCanvas},
	{(void*)_m, "primitiveCreateDefaultTypeface\000\377", (void*)primitiveCreateDefaultTypeface},
	{(void*)_m, "primitiveCreateFontStyle\000\000", (void*)primitiveCreateFontStyle},
	{(void*)_m, "primitiveCreatePaint\000\377", (void*)primitiveCreatePaint},
	{(void*)_m, "primitiveCreateSurface\000\001", (void*)primitiveCreateSurface},
	{(void*)_m, "primitiveCreateTypefaceFromName\000\001", (void*)primitiveCreateTypefaceFromName},
	{(void*)_m, "primitiveDeleteCanvas\000\000", (void*)primitiveDeleteCanvas},
	{(void*)_m, "primitiveDeletePaint\000\000", (void*)primitiveDeletePaint},
	{(void*)_m, "primitiveDeleteSurface\000\000", (void*)primitiveDeleteSurface},
	{(void*)_m, "primitivePaintGetFontMetrics\000\000", (void*)primitivePaintGetFontMetrics},
	{(void*)_m, "primitivePaintMeasureText\000\001", (void*)primitivePaintMeasureText},
	{(void*)_m, "primitivePaintSetAntialias\000\000", (void*)primitivePaintSetAntialias},
	{(void*)_m, "primitivePaintSetColor\000\000", (void*)primitivePaintSetColor},
	{(void*)_m, "primitivePaintSetStroke\000\000", (void*)primitivePaintSetStroke},
	{(void*)_m, "primitivePaintSetStrokeJoin\000\000", (void*)primitivePaintSetStrokeJoin},
	{(void*)_m, "primitivePaintSetStrokeMiter\000\000", (void*)primitivePaintSetStrokeMiter},
	{(void*)_m, "primitivePaintSetStrokeWidth\000\000", (void*)primitivePaintSetStrokeWidth},
	{(void*)_m, "primitivePaintSetTextSize\000\000", (void*)primitivePaintSetTextSize},
	{(void*)_m, "primitivePaintSetTypeface\000\000", (void*)primitivePaintSetTypeface},
	{(void*)_m, "primitivePaintSetTypefaceFromName\000\001", (void*)primitivePaintSetTypefaceFromName},
	{(void*)_m, "primitiveSaveSurface\000\000", (void*)primitiveSaveSurface},
	{(void*)_m, "setInterpreter", (void*)setInterpreter},
	{NULL, NULL, NULL}
};

#else /* ifdef SQ_BUILTIN_PLUGIN */

signed char primitiveCanvasClipRectAccessorDepth = 0;
signed char primitiveCanvasConcatTransformAccessorDepth = 1;
signed char primitiveCanvasCopyTransformAccessorDepth = 0;
signed char primitiveCanvasDrawCircleAccessorDepth = 0;
signed char primitiveCanvasDrawColorAccessorDepth = 0;
signed char primitiveCanvasDrawLineAccessorDepth = 0;
signed char primitiveCanvasDrawOvalAccessorDepth = 0;
signed char primitiveCanvasDrawRectAccessorDepth = 0;
signed char primitiveCanvasDrawRoundedRectAccessorDepth = 0;
signed char primitiveCanvasDrawRoundedRectRadiiAccessorDepth = 0;
signed char primitiveCanvasDrawTextAccessorDepth = 1;
signed char primitiveCanvasResetMatrixAccessorDepth = 0;
signed char primitiveCanvasRestoreAccessorDepth = 0;
signed char primitiveCanvasSaveAccessorDepth = 0;
signed char primitiveCanvasScaleAccessorDepth = 0;
signed char primitiveCanvasTranslateAccessorDepth = 0;
signed char primitiveCreateCanvasAccessorDepth = 0;
signed char primitiveCreateFontStyleAccessorDepth = 0;
signed char primitiveCreateSurfaceAccessorDepth = 1;
signed char primitiveCreateTypefaceFromNameAccessorDepth = 1;
signed char primitiveDeleteCanvasAccessorDepth = 0;
signed char primitiveDeletePaintAccessorDepth = 0;
signed char primitiveDeleteSurfaceAccessorDepth = 0;
signed char primitivePaintGetFontMetricsAccessorDepth = 0;
signed char primitivePaintMeasureTextAccessorDepth = 1;
signed char primitivePaintSetAntialiasAccessorDepth = 0;
signed char primitivePaintSetColorAccessorDepth = 0;
signed char primitivePaintSetStrokeAccessorDepth = 0;
signed char primitivePaintSetStrokeJoinAccessorDepth = 0;
signed char primitivePaintSetStrokeMiterAccessorDepth = 0;
signed char primitivePaintSetStrokeWidthAccessorDepth = 0;
signed char primitivePaintSetTextSizeAccessorDepth = 0;
signed char primitivePaintSetTypefaceAccessorDepth = 0;
signed char primitivePaintSetTypefaceFromNameAccessorDepth = 1;
signed char primitiveSaveSurfaceAccessorDepth = 0;

#endif /* ifdef SQ_BUILTIN_PLUGIN */
